-- SPCS Role and Privilege Setup Script
-- Run this with ACCOUNTADMIN privileges

USE ROLE ACCOUNTADMIN;

-- Create SPCS role
CREATE ROLE IF NOT EXISTS SPCS_ROLE;

-- Grant basic privileges to SPCS role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SPCS_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SPCS_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SPCS_ROLE;

-- Grant SPCS-specific privileges
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SPCS_ROLE;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE SPCS_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE SPCS_ROLE;

-- Create database and schema for SPCS first
CREATE DATABASE IF NOT EXISTS SPCS_DB;
USE DATABASE SPCS_DB;
CREATE SCHEMA IF NOT EXISTS SPCS_SCHEMA;

-- Now grant CREATE IMAGE REPOSITORY on the schema (not account)
GRANT CREATE IMAGE REPOSITORY ON SCHEMA SPCS_DB.SPCS_SCHEMA TO ROLE SPCS_ROLE;
GRANT CREATE SERVICE ON SCHEMA SPCS_DB.SPCS_SCHEMA TO ROLE SPCS_ROLE;

-- Grant privileges on database and schema
GRANT ALL PRIVILEGES ON DATABASE SPCS_DB TO ROLE SPCS_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA SPCS_DB.SPCS_SCHEMA TO ROLE SPCS_ROLE;

-- Grant SPCS role to your user (replace with your username)
GRANT ROLE SPCS_ROLE TO USER JGILSTRAP;

-- Switch to SPCS role and create resources
USE ROLE SPCS_ROLE;
USE DATABASE SPCS_DB;
USE SCHEMA SPCS_SCHEMA;

-- Create a compute pool
CREATE COMPUTE POOL IF NOT EXISTS MY_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 3600;

-- Create image repository
CREATE IMAGE REPOSITORY IF NOT EXISTS MY_IMAGE_REPO;

-- Show current setup
SELECT 'Setup completed successfully' AS STATUS;
SHOW COMPUTE POOLS;
SHOW IMAGE REPOSITORIES;